// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"database/sql"
)

type MedicalOrder struct {
	ID      int32
	Message sql.NullString
}

type Patient struct {
	ID      int32
	Name    sql.NullString
	OrderID sql.NullInt32
}
