openapi: 3.0.0
info:
  version: "1.0.0"
  title: Mange Patient
  description: >-
    Patient, and Order
paths:
  /patients:
    get:
      summary: Return all patients
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Patient"
                type: array
        '500':
          $ref: '#/components/responses/500'
  /orders/{id}:
    put:
      summary: Update a medical order
      parameters:
        - in: path
          name: id
          required: true
          description: Order ID
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        '400':
          $ref: '#/components/responses/500'
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    Patient:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        order:
          $ref: "#/components/schemas/Order"
    Order:
      type: object
      properties:
        id:
          type: string
        message:
          type: string
    ErrorResponse:
      type: array
      items:
        type: string
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
